import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import GeoLocation from '../components/GeoLocation'


export default function Home() {
  return (
    <div className='max-w-xl mx-auto mt-10 flex items-center justify-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href='/admin' ><p className='text-2xl cursor-pointer font-bold'>ADMIN PANEL</p></Link>
        <GeoLocation/>
      </main>
    </div>
  )
}
